// src/components/Sidebar.jsx
import React, { useState } from 'react';
import { 
  LayoutDashboard, 
  Users, 
  Settings, 
  UserCircle, 
  ChevronLeft, 
  ChevronRight 
} from 'lucide-react';
import { useLocation, Link } from 'react-router-dom';

const Sidebar = () => {
  const [isCollapsed, setIsCollapsed] = useState(false);
  const location = useLocation();

  const menuItems = [
    { name: 'Dashboard', path: '/', icon: LayoutDashboard },
    { name: 'Users', path: '/users', icon: Users },
    { name: 'Profile', path: '/profile', icon: UserCircle },
    { name: 'Settings', path: '/settings', icon: Settings },
  ];

  return (
    <aside 
      className={`bg-gray-900 text-white transition-all duration-300 ease-in-out flex flex-col h-screen ${
        isCollapsed ? 'w-20' : 'w-64'
      }`}
    >
      <div className="p-4 flex items-center justify-between border-b border-gray-800">
        {!isCollapsed && <span className="font-bold text-xl">AppLogo</span>}
        <button 
          onClick={() => setIsCollapsed(!isCollapsed)}
          className="p-2 hover:bg-gray-800 rounded-lg transition-colors"
        >
          {isCollapsed ? <ChevronRight size={20} /> : <ChevronLeft size={20} />}
        </button>
      </div>

      <nav className="flex-1 mt-4 px-3 space-y-2">
        {menuItems.map((item) => {
          const isActive = location.pathname === item.path;
          return (
            <Link
              key={item.path}
              to={item.path}
              className={`flex items-center p-3 rounded-lg transition-colors group ${
                isActive 
                  ? 'bg-blue-600 text-white' 
                  : 'text-gray-400 hover:bg-gray-800 hover:text-white'
              }`}
            >
              <item.icon className={`size-6 ${isActive ? 'text-white' : 'text-gray-400 group-hover:text-white'}`} />
              {!isCollapsed && <span className="ml-3 font-medium">{item.name}</span>}
            </Link>
          );
        })}
      </nav>
    </aside>
  );
};

export default Sidebar;

// src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './sidebar.component.html'
})
export class SidebarComponent {
  isCollapsed = false;

  navItems = [
    { path: '/dashboard', label: 'Dashboard', icon: 'bi-speedometer2' },
    { path: '/users', label: 'Users', icon: 'bi-people' },
    { path: '/settings', label: 'Settings', icon: 'bi-gear' },
    { path: '/profile', label: 'Profile', icon: 'bi-person' },
  ];

  toggleSidebar() {
    this.isCollapsed = !this.isCollapsed;
  }
}

<div 
  [class.w-64]="!isCollapsed" 
  [class.w-20]="isCollapsed" 
  class="h-screen flex flex-col transition-all duration-300 ease-in-out border-r border-gray-200 dark:border-gray-800 bg-[var(--bg-color)] text-[var(--text-color)]"
>
  <!-- Sidebar Header -->
  <div class="h-16 flex items-center justify-between px-4 border-b border-gray-200 dark:border-gray-800">
    <div class="flex items-center gap-3 overflow-hidden">
      <div class="min-w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
        J
      </div>
      <span *ngIf="!isCollapsed" class="font-bold text-lg truncate transition-opacity duration-300 opacity-100">
        Jarvis App
      </span>
    </div>
    <button 
      (click)="toggleSidebar()" 
      class="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-500 dark:text-gray-400 transition-colors duration-200"
    >
      <i class="bi bi-list text-xl"></i>
    </button>
  </div>

  <!-- Navigation -->
  <nav class="flex-1 py-6 px-3 overflow-y-auto overflow-x-hidden space-y-8">
    <div>
      <p *ngIf="!isCollapsed" class="px-4 text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
        Main Menu
      </p>
      <ul class="space-y-1">
        <li *ngFor="let item of navItems">
          <a 
            [routerLink]="item.path" 
            routerLinkActive="bg-blue-50 text-blue-600 dark:bg-blue-900/20 dark:text-blue-400"
            class="flex items-center p-2 rounded-lg transition-all duration-200 group cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-600 dark:text-gray-400"
          >
            <i [class]="'bi ' + item.icon + ' text-lg min-w-[24px] text-center'"
               [class.mr-3]="!isCollapsed"
               [class.mx-auto]="isCollapsed">
            </i>
            <span 
              *ngIf="!isCollapsed" 
              class="font-medium truncate transition-opacity duration-300"
            >
              {{ item.label }}
            </span>
          </a>
        </li>
      </ul>
    </div>
  </nav>

  <!-- Footer/User Section -->
  <div class="p-4 border-t border-gray-200 dark:border-gray-800">
    <div class="flex items-center p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors cursor-pointer group">
       <div class="w-9 h-9 rounded-full bg-gradient-to-tr from-blue-500 to-blue-600 flex items-center justify-center text-white font-bold text-xs flex-shrink-0" [class.mr-3]="!isCollapsed">
         AD
       </div>
       <div *ngIf="!isCollapsed" class="flex flex-col truncate overflow-hidden">
         <span class="text-sm font-semibold truncate">Admin User</span>
         <span class="text-xs text-gray-500 truncate">admin@jarvis.ai</span>
       </div>
    </div>
  </div>
</div>
